language: node_js
node_js:
  - "10"

jobs:
  include:
    - stage: install 
      script: "npm install"
    - stage: test
      script: "npm run build"

notifications:
  email:
    recipients:
    - zachcalvert+travisci-npm@gmail.com
    on_success: change
    on_failure: always
