language: node_js
node_js:
  - "10"

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${API_TOKEN}" > .npmrc

deploy:
  provider: script
  script: "npm publish"
  skip_cleanup: true
  on:
    tags: true

jobs:
  include:
    - stage: test
      script: "npm run build"

notifications:
  email:
    recipients:
    - zachcalvert+travisci-npm@gmail.com
    on_success: change
    on_failure: always
