language: node_js
node_js:
  - "10"

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${API_TOKEN}" > .npmrc

jobs:
  include:
    - stage: install 
      script: "npm install"
    - stage: test
      script: "npm run build"
    - stage: release
      node_js: "10"
      script: "npm publish"

notifications:
  email:
    recipients:
    - zachcalvert+travisci-npm@gmail.com
    on_success: change
    on_failure: always
